// :Scopy Grammar 2018
//
// Parser Class Definition File

// SHELL GENERATED BY PARSERGEN VERSION 5.0.4

#ifndef PARSER
#define PARSER

#include <string>
using namespace std;

#include "cscScan.h" // scanner class definition

#include "cscCode.h" // code generator class definition

class Parser
{
public:

	Parser();

	void SystemGoal();

private:

	Token savedToken;
	bool  tokenAvailable;

	void SyntaxError(Token t, string msg);

	Token NextToken();

	void Match(Token t);

	void ListType();

	void InitValue(ExprRec& exprRec);

	void VarDecTail(ExprRec& exprRec);

	void Init(ExprRec& exprRec);

	void VarDecList(ExprRec& exprRec);

	void DecTail();

	void Declaration();

	void ScribbleType(ExprRec& expr);

	void SizeSpec(ExprRec& expr);

	void Type(ExprRec& exprRec);

	void Literal(ExprRec& expr);

	void MultOp();

	void FactorTail(ExprRec& expr);

	void Primary(ExprRec& expr);

	void AddOp();

	void ExprTail(ExprRec& expr);

	void Factor(ExprRec& expr);

	void RelOp();

	void CondTail();

	void FloatListTail();

	void FloatList();

	void IntListTail();

	void IntList();

	void ForAssign();

	void ElseClause();

	void Condition();

	void ForStmt();

	void DoStmt();

	void WhileStmt();

	void IfStmt();

	void ItemListTail();

	void ItemList();

	void VariableTail();

	void VarListTail();

	void VarList();

	void Expression(ExprRec& expr);

	void Variable(ExprRec& identifer);

	void BreakStmt();

	void NewlineStmt();

	void OutputStmt();

	void InputStmt();

	void AssignStmt();

	void StructStmt();

	void SimpleStmt();

	void StmtTail();

	void Statement();

	void StmtList();

	void DecList();

	void Program();

}; // end of Parser class

#endif
